# Generated by Django 4.1.7 on 2023-07-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_alter_purchase_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimates',
            name='user',
        ),
        migrations.DeleteModel(
            name='EstimateItems',
        ),
        migrations.DeleteModel(
            name='Estimates',
        ),
    ]
