# Generated by Django 4.1.7 on 2023-08-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_estimate_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estimate_comments',
        ),
    ]
