# Generated by Django 4.1.7 on 2023-08-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_estimate_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='inv',
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
        migrations.DeleteModel(
            name='invoice_item',
        ),
    ]
