# Generated by Django 4.1.7 on 2023-09-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0014_invoice_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retaineritems',
            name='retainer',
        ),
        migrations.DeleteModel(
            name='RetainerInvoice',
        ),
        migrations.DeleteModel(
            name='Retaineritems',
        ),
    ]
