# Generated by Django 4.1.7 on 2023-09-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_retainer_invoice_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychellan',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChallanItems',
        ),
        migrations.DeleteModel(
            name='DeliveryChellan',
        ),
    ]
