# Generated by Django 4.1.7 on 2023-09-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0020_delivery_chellan_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invoice_item',
        ),
    ]
